package bl;

/**
 * Created by Akshay Hegde on 10/4/2019.
 *
 389. Find the Difference
 Easy

 563

 246

 Favorite

 Share
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        char xor =0;
        for (int i = 0; i < s.length(); i++) {
            xor= (char) (xor^s.charAt(i)^t.charAt(i));
        }
        xor^=t.charAt(t.length()-1);
        return xor;
    }
}
